semi: true  # Print semicolons at the ends of statements.
trailingComma: "es5"
tabWidth: 2  # Specify the number of spaces per indentation-level.
singleQuote: true  # Use single quotes instead of double quotes.
printWidth: 100  # Specify the line length that the printer will wrap on.
bracketSpacing: true # Print spaces between brackets in object literals.
bracketSameLine: true
arrowParens: "always"
