env:
  browser: true
  es2021: true
extends:
  - google
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 13
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  no-unused-vars: off
  '@typescript-eslint/no-unused-vars': warn
  valid-jsdoc:
    - error
    - 
      requireReturnType: false
      requireParamType: false
      requireReturn: false
  max-len:
    - error
    - 100
    - 2
    -
      ignoreUrls: true
      ignoreComments: false
      ignoreRegExpLiterals: true
      ignoreStrings: true
      ignoreTemplateLiterals: true

