# Include parentheses around a sole arrow function parameter.
arrowParens: always
# Print spaces between brackets in object literals.
bracketSpacing: false
# Specify the line length that the printer will wrap on.
printWidth: 100
# Print semicolons at the ends of statements.
semi: true
# Use single quotes instead of double quotes.
singleQuote: true
# Print trailing commas wherever possible in multi-line comma-separated
# syntactic structures. 
# (A single-line array, for example, never gets trailing commas.)
trailingComma: es5
